name: medapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Icons
  cupertino_icons: ^1.0.8
  badges: ^3.1.2
  
  # Push Notification Dependencies (OHNE Firebase!)
  flutter_local_notifications: ^16.3.3
  
  # API Calls und WebSocket
  http: ^1.4.0
  web_socket_channel: ^2.4.5
  
  # State Management & Storage
  provider: ^6.1.5
  shared_preferences: ^2.5.3

  # Galery Connector
  image_picker: ^0.8.6
  # QR Code Import in Database
  qr_code_scanner: ^0.7.0
  # QR Code Manipulation
  qr_code_tools: ^0.2.0
  uni_links: ^0.5.1
  flutter_dotenv: ^5.0.2
  flutter_secure_storage: ^8.0.0
  google_fonts: ^4.0.4


  geolocator: ^10.0.0        # Standort
  flutter_map: ^6.1.0        # OSM-Karte
  latlong2: ^0.9.1           # Koordinaten
  flutter_animate: ^4.5.0    # Fancy-Animationen
  lottie: ^3.0.0
  geocoding: ^3.0.0
  vibration: ^1.8.4
  awesome_snackbar_content: ^0.1.0
  path_provider: ^2.0.0
  share_plus: ^10.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/location.json

