name: medapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Icons
  cupertino_icons: ^1.0.8
  badges: ^3.1.2
  
  # Push Notification Dependencies (OHNE Firebase!)
  flutter_local_notifications: ^16.3.3
  
  # API Calls und WebSocket
  http: ^1.4.0
  web_socket_channel: ^2.4.5
  
  # State Management & Storage
  provider: ^6.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true