name: medapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Icons
  cupertino_icons: ^1.0.8
  badges: ^3.1.2
  
  # Push Notification Dependencies (OHNE Firebase!)
  flutter_local_notifications: ^19.3.0
  
  # API Calls und WebSocket
  http: ^1.4.0
  web_socket_channel: ^3.0.3
  
  # State Management & Storage
  provider: ^6.1.5
  shared_preferences: ^2.5.3

  image_picker: ^1.1.2
  qr_code_scanner: ^1.0.1
  qr_code_tools: ^0.2.0
  uni_links: ^0.5.1
  flutter_dotenv: ^5.0.2
  flutter_secure_storage: ^9.2.4
  google_fonts: ^6.2.1


  geolocator: ^14.0.2
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  flutter_animate: ^4.5.0
  lottie: ^3.0.0
  geocoding: ^4.0.0
  vibration: ^3.1.3
  awesome_snackbar_content: ^0.1.0
  path_provider: ^2.0.0
  share_plus: ^11.0.0
  firebase_core: ^3.15.1
  firebase_messaging: ^15.2.9



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/location.json
    - .env

